# Generated by Django 3.1.2 on 2020-11-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('telephone', models.CharField(default='no hay', max_length=20, unique=True)),
                ('plate', models.CharField(default='NA', max_length=10, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=20)),
                ('rh_type', models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State_location',
            fields=[
                ('State', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Zip', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('videogame_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('Early childhood', 'EC'), ('Every one', 'E'), ('Every one 10+', 'E10+'), ('Teen', 'T'), ('Mature', 'M'), ('Rating Pending', 'RP'), ('Adults', 'A')], default='Rating Pending', max_length=20)),
                ('release_date', models.DateField()),
                ('engine', models.CharField(choices=[('Unity', 'Unity'), ('Unreal', 'Unreal'), ('GameMaker', 'GameMaker'), ('Godot', 'Godot'), ('AppGameKit', 'AppGameKit'), ('CryEngine', 'CryEngine'), ('Amazon lumberyard', 'Amazon lumberyard'), ('RPG Maker', 'RPG Maker'), ('Lib GDX', 'Lib GDX')], max_length=50)),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.PROTECT, to='gde.category')),
                ('formats', models.ManyToManyField(to='gde.Format')),
                ('genre', models.ManyToManyField(to='gde.Genre')),
                ('language', models.ManyToManyField(to='gde.Language')),
                ('platform', models.ManyToManyField(to='gde.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Store_location',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.state_location')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('street_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.store_location')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='gde.category')),
                ('videogames', models.ManyToManyField(to='gde.Videogame')),
            ],
        ),
        migrations.CreateModel(
            name='Dlc',
            fields=[
                ('dlc_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Release_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.PROTECT, to='gde.category')),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gde.videogame')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_date', models.DateField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gde.shopping_cart')),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.dispatcher')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.store')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart_videogames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gde.shopping_cart')),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.videogame')),
            ],
            options={
                'unique_together': {('cart', 'videogame')},
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart_packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gde.shopping_cart')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.package')),
            ],
            options={
                'unique_together': {('cart', 'package')},
            },
        ),
        migrations.CreateModel(
            name='Shopping_cart_dlc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gde.shopping_cart')),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.dlc')),
            ],
            options={
                'unique_together': {('cart', 'dlc')},
            },
        ),
    ]
