# Generated by Django 3.1.2 on 2020-11-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0002_auto_20201119_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
