# Generated by Django 3.1.2 on 2020-11-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0003_store_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
