# Generated by Django 3.1.2 on 2020-11-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0004_dispatcher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_location2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.RemoveField(
            model_name='store_location',
            name='state',
        ),
        migrations.DeleteModel(
            name='State_location',
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gde.store_location2'),
        ),
        migrations.DeleteModel(
            name='Store_location',
        ),
    ]
