# Generated by Django 3.1.2 on 2020-11-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0005_auto_20201120_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_location2',
            new_name='Store_location',
        ),
    ]
