# Generated by Django 3.1.2 on 2020-11-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0006_auto_20201120_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
