# Generated by Django 3.1.2 on 2020-11-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gde', '0008_auto_20201123_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dlc/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, upload_to='package/%Y/%m/%d/'),
        ),
    ]
